# Generated by Django 4.1.3 on 2022-11-01 15:41

import RDEDocuments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RDEDocuments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="rdedocument",
            managers=[],
        ),
        migrations.AlterField(
            model_name="rdedocument",
            name="enrollment_parameters",
            field=models.JSONField(
                null=True, validators=[RDEDocuments.models.validate_enrollment_data]
            ),
        ),
    ]
