# Generated by Django 4.1.3 on 2022-11-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keyserver.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RDEDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_parameters",
                    models.JSONField(
                        null=True,
                        validators=[keyserver.models.validate_enrollment_data],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RDE document",
                "verbose_name_plural": "RDE documents",
            },
        ),
    ]
